#!/bin/sh
# SPDX-License-Identifier: MIT-0
# Rebuild checked-in ../wzmp3.c and ../wzmp3.h from these original C89 files.
set -eu
CDIR=$(CDPATH= cd "$(dirname -- "$0")" && pwd)
TARGET=$(dirname "$CDIR")
HEADER="$TARGET/wzmp3.h"
SOURCE="$TARGET/wzmp3.c"
TMPH="$HEADER.tmp.$$"
TMPC="$SOURCE.tmp.$$"
trap 'rm -f "$TMPH" "$TMPC"' 0 1 2 3 15
{
  echo '/* Generated by wzmp3-src/amalgamate.sh; do not edit directly.'
  echo ' * Source code MIT-0; codebook data from minimp3, CC0-1.0.'
  echo ' */'
  echo '#ifndef WZMP3_AMALGAMATED_H'
  echo '#define WZMP3_AMALGAMATED_H'
  echo '#include <stddef.h>'
  for part in memory core ppm regions granule binary spectral mpeg make join decode tail codebooks; do
    echo "/* ===== BEGIN wzmp3_${part}.h ===== */"
    sed '/^#include "wzmp3_[a-z_]*\.h"/d' "$CDIR/wzmp3_${part}.h"
    echo "/* ===== END wzmp3_${part}.h ===== */"
  done
  echo '#endif /* WZMP3_AMALGAMATED_H */'
} > "$TMPH"
{
  echo '/* Generated by wzmp3-src/amalgamate.sh; do not edit directly.'
  echo ' * Source code MIT-0; codebook data from minimp3, CC0-1.0.'
  echo ' */'
  echo '#include "wzmp3.h"'
  for part in memory core ppm binary regions granule spectral mpeg tail make join decode codebooks; do
    echo "/* ===== BEGIN wzmp3_${part}.c ===== */"
    sed '/^#include "wzmp3_[a-z_]*\.h"/d' "$CDIR/wzmp3_${part}.c"
    echo "/* ===== END wzmp3_${part}.c ===== */"
  done
} > "$TMPC"
mv "$TMPH" "$HEADER"
mv "$TMPC" "$SOURCE"
