/* Generated by wzmp3-src/amalgamate.sh; do not edit directly.
 * Source code MIT-0; codebook data from minimp3, CC0-1.0.
 */
#ifndef WZMP3_AMALGAMATED_H
#define WZMP3_AMALGAMATED_H
#include <stddef.h>
/* ===== BEGIN wzmp3_memory.h ===== */
/* SPDX-License-Identifier: MIT-0
 * Per-decoder, C89 allocation accounting. Each block includes its header in
 * the budget. Does not claim to account for the platform malloc overhead.
 */
#ifndef WZMP3_MEMORY_H
#define WZMP3_MEMORY_H
#include <stddef.h>
typedef struct wzmp3_memory_s {
    size_t current, peak, limit;
    int exhausted;
} wzmp3_memory;
void wzmp3_memory_init(wzmp3_memory *m, size_t limit);
void *wzmp3_memory_alloc(wzmp3_memory *m, size_t count);
void *wzmp3_memory_calloc(wzmp3_memory *m, size_t count, size_t size);
void *wzmp3_memory_realloc(wzmp3_memory *m, void *ptr, size_t count);
void wzmp3_memory_free(wzmp3_memory *m, void *ptr);
#endif
/* ===== END wzmp3_memory.h ===== */
/* ===== BEGIN wzmp3_core.h ===== */
/* SPDX-License-Identifier: MIT-0
 * WinZip Method 94 / packMP3 1.0 independently written decoder primitives.
 * Complete reconstruction uses wzmp3_decode plus MPEG Huffman codebooks.
 */
#ifndef WZMP3_CORE_H
#define WZMP3_CORE_H

/* Callback returns 1 and fills *byte, or 0 on failure. */
typedef int (*wzmp3_read_cb)(void *opaque, unsigned char *byte);

typedef struct wzmp3_input_s {
    wzmp3_read_cb read;
    void *opaque;
    unsigned long remaining_hi;
    unsigned long remaining_lo;
    unsigned long consumed_hi;
    unsigned long consumed_lo;
    unsigned int bit_left;
    unsigned int bit_byte;
    unsigned int virtual_bits;
    int failed;
    wzmp3_memory *memory; /* set only for duration of a decode */
} wzmp3_input;

typedef struct wzmp3_header_s {
    unsigned int samplerate;
    unsigned int channels;
    unsigned int channel_mode;
    unsigned int bitrate_kbps;   /* 0 indicates per-frame bitrate */
    unsigned int has_padding;
    unsigned int has_ms_stereo;
    unsigned int has_intensity_stereo;
    unsigned int has_special_blocks;
    unsigned int has_subblock_gain;
    unsigned int has_scf_sharing;
    unsigned int has_preemphasis;
    unsigned int has_coarse_scf;
    unsigned int protection_bit;
    unsigned int original_bit;
    unsigned int copyright_bit;
    unsigned int private_bit;
    unsigned int emphasis;
    unsigned int has_leading_bytes;
    unsigned int has_trailing_bytes;
    unsigned int has_bit_reservoir;
    unsigned int has_special_differences;
    unsigned int has_damaged_first_frames;
    unsigned long frame_count;
} wzmp3_header;

typedef struct wzmp3_range_s {
    wzmp3_input *source;
    unsigned long lower;
    unsigned long upper;
    unsigned long tag;
    unsigned long quantum;
    unsigned int pending;
    int failed;
} wzmp3_range;

void wzmp3_input_init(wzmp3_input *s, wzmp3_read_cb cb, void *opaque,
                      unsigned long length_hi, unsigned long length_lo);
int wzmp3_input_octet(wzmp3_input *s, unsigned char *out);
int wzmp3_parse_header(wzmp3_input *s, wzmp3_header *out);
/* Optional verbatim repair records precede the arithmetic stream.
 * The caller owns the allocated byte buffer and must free() it.
 */
int wzmp3_read_repairs(wzmp3_input *s, const wzmp3_header *h,
                       unsigned char **data, unsigned int *length);

/* Arithmetic part operates on unsigned integers up to exactly 31 bits.
 * This is the primitive; adaptive statistical contexts are not yet present.
 */
int wzmp3_range_init(wzmp3_range *d, wzmp3_input *s);
int wzmp3_range_count(wzmp3_range *d, unsigned long scale,
                      unsigned long *count);
int wzmp3_range_remove(wzmp3_range *d, unsigned long scale,
                       unsigned long bottom, unsigned long top);

#endif
/* ===== END wzmp3_core.h ===== */
/* ===== BEGIN wzmp3_ppm.h ===== */
/* SPDX-License-Identifier: MIT-0 */
#ifndef WZMP3_PPM_H
#define WZMP3_PPM_H

typedef struct wzmp3_ppm_node_s wzmp3_ppm_node;

typedef struct wzmp3_ppm_model_s {
    wzmp3_memory *memory;
    unsigned int alphabet;
    unsigned int context_alphabet;
    unsigned int order;
    unsigned int threshold;
    unsigned long allocated;
    unsigned long node_limit;
    wzmp3_ppm_node *all_nodes;
    wzmp3_ppm_node *active[5];
    wzmp3_ppm_node *root;
} wzmp3_ppm_model;

int wzmp3_ppm_init(wzmp3_ppm_model *m, unsigned int alphabet,
                   unsigned int context_alphabet, unsigned int order,
                   unsigned int threshold, unsigned long node_limit,
                   wzmp3_memory *memory);
void wzmp3_ppm_cleanup(wzmp3_ppm_model *m);
int wzmp3_ppm_shift(wzmp3_ppm_model *m,unsigned int context);
int wzmp3_ppm_flush(wzmp3_ppm_model *m,unsigned int shift);
int wzmp3_ppm_decode(wzmp3_ppm_model *m,wzmp3_range *r,
                     unsigned int *symbol);
#endif
/* ===== END wzmp3_ppm.h ===== */
/* ===== BEGIN wzmp3_regions.h ===== */
/* SPDX-License-Identifier: MIT-0
 * Independent MPEG-1 Layer III granule region reconstruction for WZ-MP3.
 * Not a complete MP3 decoder; fields stored in channel-major order.
 */
#ifndef WZMP3_REGIONS_H
#define WZMP3_REGIONS_H

typedef struct wzmp3_granule_s {
    unsigned int sw, type, gain, slength;
    unsigned int big_values;
    unsigned int part_length, mixed;
    unsigned int r0, r1;
    unsigned int table[3], small_table;
    unsigned int bound[3];
    unsigned int share, preflag, coarse, subgain[3];
} wzmp3_granule;

/* Requires the switch, block-type, global gain, and scalefactor-compress
 * fields to have been decoded. Exactly 2 * frame_count granules per channel.
 * Returns zero for corruption, unsupported arguments, or allocation failure.
 */
int wzmp3_regions_decode(wzmp3_range *ar, const wzmp3_header *h,
                         wzmp3_granule *granules);
/* Each granule has 36 output slots: 21 long scalefactors or 3 x 12
 * short scalefactors. The buffer holds channel-major granules.
 */
int wzmp3_scalefactors_decode(wzmp3_range *ar, const wzmp3_header *h,
                             const wzmp3_granule *g,
                             unsigned char *out);
int wzmp3_ms_stereo_decode(wzmp3_range *ar, const wzmp3_header *h,
                           unsigned char *flags);
int wzmp3_scalefactor_controls_decode(wzmp3_range *ar,
                                     const wzmp3_header *h,
                                     wzmp3_granule *granules);
#endif
/* ===== END wzmp3_regions.h ===== */
/* ===== BEGIN wzmp3_granule.h ===== */
/* SPDX-License-Identifier: MIT-0
 * Incremental Method 94 per-granule state (development API).
 * DOES NOT implement MPEG spectral coefficients, bit reservoir, or output.
 */
#ifndef WZMP3_GRANULE_H
#define WZMP3_GRANULE_H

typedef struct {
    wzmp3_memory *memory;
    wzmp3_ppm_model *scale_models;
    wzmp3_ppm_model small_bound;
    wzmp3_ppm_model damaged_bound;
    unsigned char long_history[2][21];
    unsigned char short_history[2][12];
    unsigned char sharing[2][4];
    unsigned int last_bound[2];
    unsigned int channel_count;
    unsigned long step;
    unsigned long total_steps;
    int ready;
    int pending_bound;
} wzmp3_granule_state;

int wzmp3_granule_init(wzmp3_granule_state *st, const wzmp3_header *h, wzmp3_memory *memory);
/* Call exactly once for each granule in frame/granule/channel order.
 * Spectral decoding MUST be performed between successive calls by the
 * eventual complete decoder; this API does not do it on its own.
 */
int wzmp3_granule_scalefactors(wzmp3_granule_state *st,
                              wzmp3_range *range,
                              const wzmp3_granule *g,
                              unsigned int channel,
                              unsigned int granule_within_frame,
                              unsigned char result[36]);
/* Decode the next per-granule spectral-region bound; updates region limits
 * only for the damaged-frame extension defined by the stream format.
 */
int wzmp3_granule_small_bound(wzmp3_granule_state *st,
                             wzmp3_range *range,
                             wzmp3_granule *g,
                             unsigned int channel,
                             unsigned int *small_bound);
void wzmp3_granule_destroy(wzmp3_granule_state *st);
#endif
/* ===== END wzmp3_granule.h ===== */
/* ===== BEGIN wzmp3_binary.h ===== */
/* SPDX-License-Identifier: MIT-0
 * Order-one adaptive binary arithmetic contexts for Method 94.
 */
#ifndef WZMP3_BINARY_H
#define WZMP3_BINARY_H
typedef struct wzmp3_binary_s {
    unsigned short freq[16][2];
    unsigned int current;
} wzmp3_binary;
void wzmp3_binary_init(wzmp3_binary *model);
int wzmp3_binary_shift(wzmp3_binary *model,unsigned int context);
int wzmp3_binary_decode(wzmp3_binary *model,wzmp3_range *r,
                        unsigned int *symbol);
void wzmp3_binary_flush(wzmp3_binary *model,unsigned int shift);
#endif
/* ===== END wzmp3_binary.h ===== */
/* ===== BEGIN wzmp3_spectral.h ===== */
/* SPDX-License-Identifier: MIT-0
 * Adaptive coefficient and inter-granule stuffing reader for WZ-MP3 1.0.
 * This module emits decoded symbols, not MPEG Huffman-coded output.
 */
#ifndef WZMP3_SPECTRAL_H
#define WZMP3_SPECTRAL_H

typedef struct wzmp3_bin2_s {
    unsigned short frequency[16][16][2];
    unsigned int previous, current;
} wzmp3_bin2;

typedef struct wzmp3_spectral_s {
    wzmp3_memory *memory;
    wzmp3_ppm_model *magnitudes[2][8][32];
    wzmp3_bin2 *small[2][8][2];
    wzmp3_bin2 *signs[2][8];
    wzmp3_ppm_model *lengths[2][14];
    wzmp3_bin2 remainder;
    wzmp3_ppm_model stuffing_count;
    wzmp3_binary stuffing_bits;
    unsigned char history_abs[2][2][580];
    unsigned char history_sign[2][2][580];
    unsigned char history_len[2][2][580];
    unsigned char retained_width[2][576];
    unsigned int last_stuff_count,last_stuff_bit;
    unsigned int channels,joint;
    int initialized;
} wzmp3_spectral;

typedef struct wzmp3_spectrum_s {
    unsigned char magnitude[576],negative[576],extra_width[576];
    unsigned short extra_bits[576];
    unsigned int small_boundary;
    unsigned int stuffing_count;
    unsigned char stuffing_bits[4096]; /* unpacked 0/1; byte output not yet implemented */
} wzmp3_spectrum;

int wzmp3_spectral_init(wzmp3_spectral *st,const wzmp3_header *header,
                        wzmp3_memory *memory);
/* Call in frame/granule/channel order; pass the current frame's ch0 block type.
 * For channel 0, ch0_type must equal granule->type, and other_type is
 * the next channel's block type (or the same type for mono).
 */
int wzmp3_spectral_read(wzmp3_spectral *st,wzmp3_range *ar,
                        const wzmp3_granule *granule,unsigned int small_boundary,
                        unsigned int channel,unsigned int ch0_type,
                        unsigned int other_type,unsigned int ms_stereo,wzmp3_spectrum *out);
void wzmp3_spectral_free(wzmp3_spectral *st);
#endif
/* ===== END wzmp3_spectral.h ===== */
/* ===== BEGIN wzmp3_mpeg.h ===== */
/* SPDX-License-Identifier: MIT-0
 * MPEG-1 Layer III bit-accurate frame serialization and Huffman output.
 * Format fields follow ISO/IEC 11172-3; no MPEG audio decoder is linked.
 */
#ifndef WZMP3_MPEG_H
#define WZMP3_MPEG_H
#include <stddef.h>
#define WZMP3_FRAME_LIMIT 2048U
#define WZMP3_HUFF_SYMBOLS 256U

typedef struct wzmp3_bitwriter_s {
    unsigned char *bytes;
    size_t capacity;
    size_t bits;
    int failed;
} wzmp3_bitwriter;

typedef struct wzmp3_codeword_s {
    unsigned long code;
    unsigned char length;
} wzmp3_codeword;

typedef struct wzmp3_codebook_s {
    wzmp3_codeword symbols[WZMP3_HUFF_SYMBOLS];
    unsigned int linbits;
    unsigned int quad;
    unsigned int maxvalue;
} wzmp3_codebook;

typedef struct wzmp3_mpeg_frame_s {
    unsigned char header[4];
    unsigned char crc[2];
    unsigned int crc_present;
    unsigned int bitrate_index, rate_index, padding;
    unsigned int channels, frame_bytes, side_bytes;
    unsigned int main_data_begin, side_private;
    unsigned int scfsi[2];
    wzmp3_granule granules[2][2];  /* [granule][channel] */
} wzmp3_mpeg_frame;

void wzmp3_bits_start(wzmp3_bitwriter *w,unsigned char *dst,size_t cap);
int wzmp3_bits_put(wzmp3_bitwriter *w,unsigned int value,unsigned int nbits);
int wzmp3_bits_put_long(wzmp3_bitwriter *w,unsigned long value,unsigned int nbits);
int wzmp3_bits_align(wzmp3_bitwriter *w);
int wzmp3_bits_size(const wzmp3_bitwriter *w,size_t *size);

int wzmp3_mpeg_parse(const unsigned char *data,size_t available,
                     wzmp3_mpeg_frame *frame);
/* Find a frame's first encoded main-data bit in the concatenation of
 * earlier and current frame main-data areas. Never resolves a filesystem
 * location or trusts an unchecked backward offset. */
int wzmp3_mpeg_main_position(const wzmp3_mpeg_frame *f,
                             size_t main_bytes_before_frame,
                             size_t *bit_position);
int wzmp3_mpeg_write_header(const wzmp3_mpeg_frame *frame,
                            unsigned char *out,size_t capacity,
                            size_t *length);
/* MPEG-1 Layer III pair: Huffman codeword, x linbits, x sign, y linbits,
 * y sign. Only the ISO table numbers' actual codewords are supplied by
 * the caller; these generic primitives do not embed LGPL codebooks.
 */
int wzmp3_huffman_pair(wzmp3_bitwriter *writer,const wzmp3_codebook *book,
                       unsigned int x,unsigned int y,
                       unsigned int xnegative,unsigned int ynegative);
int wzmp3_huffman_quad(wzmp3_bitwriter *writer,const wzmp3_codebook *book,
                       const unsigned char magnitudes[4],
                       const unsigned char negatives[4]);
/* Reconstruct one MPEG granule's Huffman-coded spectral section using the
 * standard ISO codebooks supplied by the caller. The caller separately
 * writes scalefactors and sets the resulting part2_3_length.
 */
/* Emit scalefactors from the granule reader in MPEG standard order.
 * share_flags are the first granule's SCFSI bits for this channel.
 * Mixed short/long blocks require a separately verified path.
 */
int wzmp3_mpeg_scalefactors(wzmp3_bitwriter *writer,
                            const wzmp3_granule *granule,
                            const unsigned char values[36],
                            unsigned int granule_index,
                            unsigned int share_flags);
int wzmp3_huffman_spectrum(wzmp3_bitwriter *writer,
                           const wzmp3_codebook books[34],
                           const wzmp3_granule *granule,
                           const wzmp3_spectrum *spectrum);
#endif
/* ===== END wzmp3_mpeg.h ===== */
/* ===== BEGIN wzmp3_make.h ===== */
/* SPDX-License-Identifier: MIT-0
 * Independent Method 94 reconstruction of MPEG-1 Layer III frame headers.
 */
#ifndef WZMP3_MAKE_H
#define WZMP3_MAKE_H
/* May apply repair record to the frame's original private/original/copyright,
 * reservoir, granule bit lengths, scale lengths, and big-value counts.
 * Fixed-frame headers are independently reconstructible without file access.
 * Caller must supply decoded frame/bitstream fields, never original MP3 bytes.
 */
int wzmp3_make_frame(const wzmp3_header *h,
                     const wzmp3_granule *gs,
                     unsigned int bitrate_index, unsigned int padding,
                     unsigned int middle_stereo, unsigned int reservoir,
                     unsigned long frame_index,
                     const unsigned char *repairs,unsigned int repair_len,
                     wzmp3_mpeg_frame *out);
#endif
/* ===== END wzmp3_make.h ===== */
/* ===== BEGIN wzmp3_join.h ===== */
/* SPDX-License-Identifier: MIT-0
 * WinZip Method 94: reconstruction of MPEG-1 Layer III frame byte layout.
 * Independent implementation; no MPEG Huffman/entropy codebooks included.
 */
#ifndef WZMP3_JOIN_H
#define WZMP3_JOIN_H
#include <stddef.h>

typedef struct wzmp3_join_frame_s {
    unsigned char header[40];
    size_t header_bytes;
    size_t body_bytes;
} wzmp3_join_frame;

typedef struct wzmp3_join_s {
    wzmp3_memory *memory;
    wzmp3_join_frame *frames;
    unsigned char *main_data;
    size_t main_capacity;
    size_t main_bits;
    size_t physical_bytes;
    size_t frame_count;
    size_t frames_used;
    int error;
} wzmp3_join;

typedef int (*wzmp3_write_cb)(void *,const unsigned char *,size_t);

/* main_capacity bounds the entire contiguous MPEG frame-body stream. The
 * caller may choose a stricter limit based on the ZIP uncompressed size. */
int wzmp3_join_init(wzmp3_join *j,size_t main_capacity,size_t frame_count,
                    wzmp3_memory *memory);
void wzmp3_join_free(wzmp3_join *j);
/* `audio` is the MPEG part2_3 bitstream of all granules of this frame,
 * concatenated in granule/channel order. `tail` fills the remaining bits
 * through the next reservoir start; both are packed MSB-first. */
int wzmp3_join_frame_add(wzmp3_join *j,const unsigned char *header,
                         size_t header_bytes,size_t frame_bytes,
                         unsigned int main_data_begin,
                         const unsigned char *audio,size_t audio_bits,
                         const unsigned char *tail,size_t tail_bits);
/* Emits prefix, complete frames, suffix; only callable after all physical
 * body bytes have been reconstructed exactly. A failing output callback may
 * leave partially written output; the caller must handle that failure. */
int wzmp3_join_emit(const wzmp3_join *j,
                    const unsigned char *prefix,size_t prefix_bytes,
                    const unsigned char *suffix,size_t suffix_bytes,
                    wzmp3_write_cb write,void *opaque);
#endif
/* ===== END wzmp3_join.h ===== */
/* ===== BEGIN wzmp3_decode.h ===== */
/* SPDX-License-Identifier: MIT-0
 * Standalone Method 94 decoder API. No ZIP integration.
 * Huffman tables supplied separately by independently licensed provider.
 */
#ifndef WZMP3_DECODE_H
#define WZMP3_DECODE_H
typedef struct wzmp3_decode_options_s {
    size_t maximum_output; /* hard output bound; should be ZIP uncompressed size */
    unsigned long maximum_frames;
} wzmp3_decode_options;
/* Returns 1 on success, 0 for invalid data/output error, and -1 for
 * exhausted decoder heap budget or system allocation failure. */
int wzmp3_decode(wzmp3_input *input,const wzmp3_codebook books[34],
                 const wzmp3_decode_options *options,
                 wzmp3_write_cb output,void *output_context);
#endif
/* ===== END wzmp3_decode.h ===== */
/* ===== BEGIN wzmp3_tail.h ===== */
/* SPDX-License-Identifier: MIT-0
 * packMP3 1.0 frame-tail, bitrate and reservoir bitstream reader.
 * Must be combined with independent MPEG Huffman codebooks for decoding.
 */
#ifndef WZMP3_TAIL_H
#define WZMP3_TAIL_H

typedef struct wzmp3_tail_s {
    wzmp3_ppm_model aux_model,bitrate_model;
    wzmp3_binary control_model;
    unsigned short raw_freq[256][2];
    unsigned int bitrate_kbps,has_reservoir,rate,channels,crc_present;
    unsigned int last_aux_context,pad_history;
    unsigned int predictor_phase,predictor_length,predictor_constant;
    unsigned char predictor_text[20];
    int reservoir;
    int initialized;
} wzmp3_tail;

typedef struct wzmp3_tail_result_s {
    unsigned int bitrate_index,frame_bytes;
    unsigned int main_size,main_data_begin,aux_bytes,following_reservoir;
    unsigned int payload_bits;
    unsigned char payload[2048];
} wzmp3_tail_result;
int wzmp3_tail_init(wzmp3_tail *tail,const wzmp3_header *header,
                    wzmp3_memory *memory);
int wzmp3_tail_read(wzmp3_tail *tail,wzmp3_range *ar,
                    unsigned int main_bits,unsigned int padding,
                    int last_frame,wzmp3_tail_result *out);
void wzmp3_tail_free(wzmp3_tail *tail);
#endif
/* ===== END wzmp3_tail.h ===== */
/* ===== BEGIN wzmp3_codebooks.h ===== */
/* SPDX-License-Identifier: CC0-1.0
 * Derived from the independently published minimp3.h by lieff and contributors.
 * https://github.com/lieff/minimp3
 * This is an inverse representation of its MPEG Layer III decoder tables.
 * CC0 dedication: https://creativecommons.org/publicdomain/zero/1.0/
 * No LGPL packMP3 data or code used to produce these tables.
 */
#ifndef WZMP3_CODEBOOKS_H
#define WZMP3_CODEBOOKS_H
void wzmp3_codebooks_init(wzmp3_codebook books[34]);
#endif
/* ===== END wzmp3_codebooks.h ===== */
#endif /* WZMP3_AMALGAMATED_H */
